### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by dandanvidi** [Bahler-Lab/pyphe#1]
Hello! pyphe installs well when using pip on my local mac but when trying to run it I get

dan@Dans-iMac ~ % pyphe-quantify
zsh: permission denied: pyphe-quantify

Can you please advise?

**Comment by yeastbeast** [comment]
Hi!
Sorry you are having issues, I haven't tested pyphe on macOS.
When pyphe is installed, pip copies the executable files into a folder, for me, using anaconda, this is in "anaconda3\Scripts". This folder needs to be in your PATH and the files need to be executable. You can find the folder by running "type pyphe-quantify" which will tell you its exact location. 
I think you should be able to fix your problem by going into that folder in the terminal and then giving the files execution permissions using the chmod command:
chmod +x pyphe-quantify
(and similarly with the other pyphe tools)
Please let me know if that works, I will try and figure out a better solution to make it work out of the box in the future.
Stephan

**Comment by yeastbeast** [comment]
Hi,
I will close this for now. There is a possibility that I will provide a command line interface as entry_points which should improve cross-platform compatibility.
